version: '3.4'

networks:
  kafka-network:

services:

  # Zookeeper Nodes
  zookeeper-server1:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-network
    ports:
      - '2181:2181'
    environment:
      ZOO_SERVER_ID: 1
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_SERVERS: "zookeeper-server1:2888:3888,zookeeper-server2:2888:3888,zookeeper-server3:2888:3888"
      
  zookeeper-server2:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-network
    ports:
      - '3181:2181'
    environment:
      ZOO_SERVER_ID: 2
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_SERVERS: "zookeeper-server1:2888:3888,zookeeper-server2:2888:3888,zookeeper-server3:2888:3888"
      
  zookeeper-server3:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-network
    ports:
      - '4181:2181'
    environment:
      ZOO_SERVER_ID: 3
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_SERVERS: "zookeeper-server1:2888:3888,zookeeper-server2:2888:3888,zookeeper-server3:2888:3888"
      
  # Kafka Brokers
  kafka-server1:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-network    
    ports:
      - '9092:9092'
    expose:
      - '29092'
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper-server1:2181,zookeeper-server2:3181,zookeeper-server3:4181"
      KAFKA_CFG_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "INTERNAL://kafka-server1:29092,EXTERNAL://localhost:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper-server1
      - zookeeper-server2
      - zookeeper-server3
      
  kafka-server2:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-network    
    ports:
      - '9093:9092'
    expose:
      - '39092'
    environment:
      KAFKA_BROKER_ID: 102
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper-server1:2181,zookeeper-server2:3181,zookeeper-server3:4181"
      KAFKA_CFG_LISTENERS: "INTERNAL://:39092,EXTERNAL://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "INTERNAL://kafka-server2:39092,EXTERNAL://localhost:9093"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper-server1
      - zookeeper-server2
      - zookeeper-server3
  
  kafka-server3:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-network    
    ports:
      - '9094:9092'
    expose:
      - '49092'
    environment:
      KAFKA_BROKER_ID: 103
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper-server1:2181,zookeeper-server2:3181,zookeeper-server3:4181"
      KAFKA_CFG_LISTENERS: "INTERNAL://:49092,EXTERNAL://:9094"
      KAFKA_CFG_ADVERTISED_LISTENERS: "INTERNAL://kafka-server3:49092,EXTERNAL://localhost:9094"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper-server1
      - zookeeper-server2
      - zookeeper-server3
      

  # Kafdrop for UI
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    networks:
      - kafka-network 
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka-server1:29092,kafka-server2:39092,kafka-server3:49092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - kafka-server1
      - kafka-server2
      - kafka-server3

